#
# Centralised Auth-Gateway which integrates with Traefik through forward-middleware.
#
# To learn more about the centralised auth-gateway, please refer to:
# https://cognigy.visualstudio.com/Cognigy.AI/_git/cognigy?path=/services/service-api/src/authGateway/README.md&_a=preview
#
{{- if .Values.serviceApi.serviceAuthGateway.enabled }}
{{- $statefulRabbitMq_secret := include "common.secretName.render" ( dict "existingSecret" $.Values.statefulRabbitMq.auth.existingSecret "defaultSecret" "cognigy-rabbitmq") }}
{{- $redisHa_secret := include "common.secretName.render" ( dict "existingSecret" $.Values.redisHa.auth.existingSecret "defaultSecret" "cognigy-redis-password") }}
{{- $serviceApi_dbSecret := include "common.secretName.render" ( dict "existingSecret" $.Values.dbConnectionString.services.serviceApi.auth.existingSecret "defaultSecret" (printf "cognigy-%s" $.Values.dbConnectionString.services.serviceApi.serviceName)) }}
{{- $jwtPrivateKey := include "common.secretName.render" ( dict "existingSecret" $.Values.commonSecrets.authGatewayKeyPair.existingPrivateKeySecret "defaultSecret" "auth-gateway-private-key") }}
{{- with .Values.serviceApi.serviceAuthGateway }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth-gateway
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    owner-team: boron
spec:
  selector:
    matchLabels:
      app: service-auth-gateway
  replicas: {{ .replicaCount }}
  template:
    metadata:
      labels:
        app: service-auth-gateway
      annotations:
        checksum/cognigy-env: {{ include (print $.Template.BasePath "/configurations/cognigy-env.yaml") $ | sha256sum }}
        checksum/rabbitmq: {{ if not (lookup "v1" "Secret" $.Release.Namespace $statefulRabbitMq_secret) }}{{ $statefulRabbitMq_secret | sha256sum }}{{ else }}{{ toYaml (lookup "v1" "Secret" $.Release.Namespace $statefulRabbitMq_secret).data | sha256sum }}{{ end }}
        checksum/redis: {{ if not (lookup "v1" "Secret" $.Release.Namespace $redisHa_secret) }}{{ $redisHa_secret | sha256sum }}{{ else }}{{ toYaml (lookup "v1" "Secret" $.Release.Namespace $redisHa_secret).data | sha256sum }}{{ end }}
        checksum/dbSecret: {{ if not (lookup "v1" "Secret" $.Release.Namespace $serviceApi_dbSecret) }}{{ $serviceApi_dbSecret | sha256sum }}{{ else }}{{ toYaml (lookup "v1" "Secret" $.Release.Namespace $serviceApi_dbSecret).data | sha256sum }}{{ end }}
        checksum/jwtPrivateKey: {{ if not (lookup "v1" "Secret" $.Release.Namespace $jwtPrivateKey) }}{{ $jwtPrivateKey | sha256sum }}{{ else }}{{ toYaml (lookup "v1" "Secret" $.Release.Namespace $jwtPrivateKey).data | sha256sum }}{{ end }}
        {{- if $.Values.cognigyCommonPodAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" $.Values.cognigyCommonPodAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .serviceAccountName }}
      serviceAccountName: {{ .serviceAccountName }}
      {{- end }}
      {{- if .affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .priorityClassName }}
      priorityClassName: {{ .priorityClassName }}
      {{- end }}
      containers:
        - name: service-auth-gateway
          image: {{ include "common.image.render" (dict "global" $.Values.global "image" $.Values.serviceApi.image) }}
          resources: {{- toYaml .resources | nindent 12 }}
          command: ["node"]
          args: ["/app/build/authGateway/index"]
          # ports:
          #   - name: health
          #     containerPort: 8001
          #   - name: metrics
          #     containerPort: 8002
          envFrom:
            - configMapRef:
                name: cognigy-env
          env:
            - name: REDIS_ENABLE_RECONNECT
              value: "true"
            - name: RABBITMQ_ENABLE_RECONNECT
              value: "true"
            - name: AUTH_GATEWAY_JWT_PRIVATE_KEY_PATH_AND_FILENAME
              value: "/var/run/secrets/internal-auth-gateway-jwt-private-key.pem"
            {{- if .extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: rabbitmq-connection-string
              mountPath: /var/run/secrets/rabbitmqConnectionString
              subPath: rabbitmqConnectionString
            - name: mongodb-connection-string
              mountPath: /var/run/secrets/mongodbConnectionString
              subPath: mongodbConnectionString
            - name: redis-password
              mountPath: /var/run/secrets/redis-password.conf
              subPath: redis-password.conf
            - name: auth-gateway-private-key
              mountPath: /var/run/secrets/internal-auth-gateway-jwt-private-key.pem
              subPath: internal-auth-gateway-jwt-private-key.pem
            {{- if .extraVolumeMounts }}
            {{- include "common.tplvalues.render" ( dict "value" .extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
          # startupProbe:
          #   httpGet:
          #     path: /health/startup
          #     port: 8001
          # livenessProbe:
          #   httpGet:
          #     path: /health/liveness
          #     port: 8001
          #   failureThreshold: 3
          #   initialDelaySeconds: 90
          #   periodSeconds: 60
          #   timeoutSeconds: 10
      volumes:
        - name: rabbitmq-connection-string
          secret:
            secretName: {{ $statefulRabbitMq_secret }}
            items:
              - key: connection-string
                path: rabbitmqConnectionString
        # using serviceAPI DB connection string as it is also using the serviceAPI container image
        - name: mongodb-connection-string
          secret:
            secretName: {{ $serviceApi_dbSecret }}
            items:
              - key: connection-string
                path: mongodbConnectionString
        - name: redis-password
          secret:
            secretName: {{ $redisHa_secret }}
        # private key to sign short lived JWTs
        - name: auth-gateway-private-key
          secret:
            secretName: {{ $jwtPrivateKey }}
            defaultMode: 420

        {{- if .extraVolumes }}
        {{- include "common.tplvalues.render" ( dict "value" .extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
      {{- include "image.pullSecretsCognigy" $ | nindent 6 }}
      securityContext:
        {{- toYaml .securityContext | nindent 8 }}
{{- end }}
{{- end }}